/**
 * Some of this code was generated by v0 by Vercel.
 * @see https://v0.dev/t/PJm3y9BXTIt
 */
import Link from "next/link"
import { useWeb3Modal } from '@web3modal/wagmi/react'
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import {ConnectButton} from "@rainbow-me/rainbowkit"
import {Wallet, CalendarDays, BarChart, ArrowUpRight } from "lucide-react"
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export function Dashboardv2() {
  
  return (
    <div className="flex flex-col h-screen">
      <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-10">
        <ConnectButton />
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
          <Card>
            <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
              <CardTitle className="text-sm font-medium">Wallet Balance</CardTitle>
              <Wallet className="w-4 h-4 text-gray-500 dark:text-gray-400" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">$12,345.67</div>
              <p className="text-xs text-gray-500 dark:text-gray-400">Total balance in your wallet</p>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
              <CardTitle className="text-sm font-medium">Transaction History</CardTitle>
              <CalendarDays className="w-4 h-4 text-gray-500 dark:text-gray-400" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">12</div>
              <p className="text-xs text-gray-500 dark:text-gray-400">Number of transactions in the last 30 days</p>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
              <CardTitle className="text-sm font-medium">Portfolio Overview</CardTitle>
              <BarChart className="w-4 h-4 text-gray-500 dark:text-gray-400" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">$5,678.90</div>
              <p className="text-xs text-gray-500 dark:text-gray-400">Value of your portfolio</p>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
              <CardTitle className="text-sm font-medium">Buy/Sell Cryptocurrency</CardTitle>
              <ArrowUpRight className="w-4 h-4 text-gray-500 dark:text-gray-400" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">$1,234.56</div>
              <p className="text-xs text-gray-500 dark:text-gray-400">Amount of cryptocurrency you've bought or sold</p>
            </CardContent>
          </Card>
        </div>
        <div>
          <Card>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="w-[100px]">Transaction</TableHead>
                  <TableHead>Type</TableHead>
                  <TableHead>Cryptocurrency</TableHead>
                  <TableHead className="text-right">Amount</TableHead>
                  <TableHead className="text-right">Status</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell className="font-medium">TX001</TableCell>
                  <TableCell>Received</TableCell>
                  <TableCell>BTC</TableCell>
                  <TableCell className="text-right">+0.5</TableCell>
                  <TableCell className="text-right">Completed</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">TX002</TableCell>
                  <TableCell>Sent</TableCell>
                  <TableCell>ETH</TableCell>
                  <TableCell className="text-right">-0.25</TableCell>
                  <TableCell className="text-right">Pending</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">TX003</TableCell>
                  <TableCell>Received</TableCell>
                  <TableCell>LTC</TableCell>
                  <TableCell className="text-right">+1.0</TableCell>
                  <TableCell className="text-right">Completed</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">TX004</TableCell>
                  <TableCell>Sent</TableCell>
                  <TableCell>XRP</TableCell>
                  <TableCell className="text-right">-2.0</TableCell>
                  <TableCell className="text-right">Completed</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">TX005</TableCell>
                  <TableCell>Received</TableCell>
                  <TableCell>ADA</TableCell>
                  <TableCell className="text-right">+3.0</TableCell>
                  <TableCell className="text-right">Completed</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </Card>
        </div>
        {/* <w3m-button /> */}
      </main>
    </div>
  )
}

